name: 'Create release'
description: 'Creates a release in github with a tag based on input parameters'
inputs:
  tag:
    description: 'Tag for release'
    required: true
  github_secret:
    description: 'Secret for github'
    required: true
  release_name:
    description: 'The name of the release, default `Release {tag}`'
    required: false
  prerelease:
    description: 'Is this a pre-release package'
    required: false
outputs:
  id:
    description: 'Release ID'
  upload_url:
    description: 'Upload URL for release'
  html_url:
    description: 'Html URL for release'
runs:
  using: 'node16'
  main: 'dist/index.js'