name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  level:
    description: 'Can be minor, major or patch'
    required: true
  build_number:
    description: 'If supplied, we will build an output with this version number in the form of {version}-alpha.{build_number}'
    required: false
outputs:
  old_version:
    description: 'Old version'
  new_version:
    description: 'New version'
  pre_release_version:
    description: 'Pre release version built from {new_version}-alpha.{build_number}'
runs:
  using: 'node16'
  main: 'dist/index.js'